services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - image_classificator
    grpc-server:
        build: ./Server
        container_name: grpc-server
        ports:
            - "9090:9090"
        networks:
            - image_classificator
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=mongodb://mongodb:27017
            - MONGO_PORT=27017
            - MONGO_DB=image_classificator
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: image_classificator
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - image_classificator
    restapi:
        build: ./Api
        container_name: restapi
        ports:
            - "3000:3000"
        networks:
            - image_classificator
        depends_on:
            - postgres_db
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres_db:5432/image_classificator
            JWT_SECRET: secret
            GRPC_HOST: grpc-server
            GRPC_PORT: 9090
    frontend:
        build: ./Client
        container_name: frontend
        ports:
            - "80:80"
        networks:
            - image_classificator
        depends_on:
            - restapi
        environment:
            - REACT_APP_API_URL=http://localhost:3000

volumes:
    mongo-data:
    postgres_data:

networks:
    image_classificator:
        driver: bridge
