services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - image_classificator
    grpc-server:
        build: ./Server
        container_name: grpc-server
        ports:
            - "9090:9090"
        networks:
            - image_classificator
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=mongodb://mongodb:27017
            - MONGO_PORT=27017
            - MONGO_DB=image_classificator
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: image_classificator
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - image_classificator
    restapi:
        build: ./Api
        container_name: restapi
        ports:
            - "3000:3000"
        networks:
            - image_classificator
        depends_on:
            - postgres_db
        environment:
            JWT_SECRET: secret
            GRPC_HOST: grpc-server
            GRPC_PORT: 9090
            PROD_DB_USERNAME: postgres
            PROD_DB_PASSWORD: postgres
            PROD_DB_NAME: image_classificator
            PROD_DB_HOST: postgres_db
            ALLOWED_ORIGINS: http://localhost:3000,http://localhost:8080
    migration:
        build: ./Api
        container_name: migration
        networks:
            - image_classificator
        depends_on:
            - postgres_db
        command: ["/usr/wait-for-it.sh", "-t", "3", "postgres:5432", "--", "npm", "run", "init"]
        environment:
            PROD_DB_USERNAME: postgres
            PROD_DB_PASSWORD: postgres
            PROD_DB_NAME: image_classificator
            PROD_DB_HOST: postgres_db
            NODE_ENV: production
    frontend:
        build: ./Client
        container_name: frontend
        ports:
            - "80:80"
        networks:
            - image_classificator
        depends_on:
            - restapi
        environment:
            VITE_BASE_URL: http://localhost:3000

volumes:
    mongo-data:
        name: mongo_data
    postgres_data:
        name: postgres_data

networks:
    image_classificator:
        name: image_classificator
        driver: bridge
