services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - mongo-data:/data/db
            - mongo-data:/data/configdb
        networks:
            - image_classificator
    grpc-server:
        build: ./Server
        container_name: grpc-server
        ports:
            - "9090:9090"
        networks:
            - image_classificator
        volumes:
            - image-data:/app/data/images
        depends_on:
            - mongodb
        environment:
            MONGO_HOST: mongodb://mongodb:27017
            MONGO_PORT: 27017
            MONGO_DB: image_classificator
            PORT: 9090
    postgresdb:
        image: postgres:latest
        container_name: postgresdb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: image_classificator
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - image_classificator
    rest-api:
        build: ./Api
        container_name: rest-api
        ports:
            - "3000:3000"
        networks:
            - image_classificator
        depends_on:
            - postgresdb
        environment:
            JWT_SECRET: secret
            GRPC_HOST: grpc-server
            GRPC_PORT: 9090
            PROD_DB_USERNAME: postgres
            PROD_DB_PASSWORD: postgres
            PROD_DB_NAME: image_classificator
            PROD_DB_HOST: postgresdb
            ALLOWED_ORIGINS: http://localhost
    migration:
        build: ./Api
        container_name: migration
        profiles: ["tools"]
        networks:
            - image_classificator
        depends_on:
            - postgresdb
        command: ["/usr/wait-for-it.sh", "-t", "3", "postgres:5432", "--", "npm", "run", "init"]
        environment:
            PROD_DB_USERNAME: postgres
            PROD_DB_PASSWORD: postgres
            PROD_DB_NAME: image_classificator
            PROD_DB_HOST: postgresdb
            NODE_ENV: production
    frontend:
        build:
            context: ./Client
            args:
                VITE_API_URL: http://localhost:3000
        container_name: frontend
        ports:
            - "80:80"
        networks:
            - image_classificator
        depends_on:
            - rest-api

volumes:
    mongo-data:
        name: image-classificator-mongo-data
    postgres_data:
        name: image-classificator-postgres-data
    image-data:
        name: image-classificator-image-data

networks:
    image_classificator:
        name: image_classificator-network
        driver: bridge
