services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - mongo-network
    grpc-server:
        build: .
        container_name: grpc-server
        ports:
            - "9090:9090"
        networks:
            - mongo-network
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=mongodb://mongodb:27017
            - MONGO_PORT=27017
            - MONGO_DB=image_classificator

volumes:
    mongo-data:

networks:
    mongo-network:
        driver: bridge
