name: Generate and Deploy Swagger Docs

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Adjust to your Node version

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: Api  # Set to the root of the Api folder
        run: npm install

      # Step 4: Generate swagger.json from specs
      - name: Generate swagger.json
        working-directory: Api  # Set to the root of the Api folder
        run: |
          node -e "const { specs } = require('./src/swagger'); const fs = require('fs'); fs.writeFileSync('./swagger.json', JSON.stringify(specs, null, 2));"

      # Step 5: Create Swagger HTML file for GitHub Pages
      - name: Create Swagger HTML file
        working-directory: Api  # Save generated files in Api folder to keep them together
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <title>API Documentation</title>
              <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist/swagger-ui.css" />
          </head>
          <style>
              /* Remove padding from the body */
              body {
                  margin: 0;
                  padding: 0;
              }
          </style>
          <body>
              <div id="swagger-ui"></div>
              <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script>
              <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-standalone-preset.js"></script>
              <script>
                  SwaggerUIBundle({
                      url: "swagger.json",  // Points to the generated JSON file
                      dom_id: "#swagger-ui",
                      presets: [
                          SwaggerUIBundle.presets.apis,
                          SwaggerUIStandalonePreset
                      ],
                      layout: "StandaloneLayout"
                  });
              </script>
          </body>
          </html>' > index.html

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: Api  # Set to Api folder where `index.html` and `swagger.json` are created
          force_orphan: true  # Creates a new commit history for the `gh-pages` branch
